name: RBGUI
main: com.saf.medievalgui.GUI
version: 18.21.1.2
load: STARTUP
commands:
  quest:
    description: Open book
    usage: /<command>
  health:
    description: HealPlayer
    usage: /<command>