name: RBEconomy
main: com.skyandforest.reboot_economy.Eco
version: 18.32.3.5
load: STARTUP
commands:
  eco:
    description: Working with player balance
    usage: /<command> [add|set <currensy> <amount>]
    aliases: [b, bal, balance, money, и, ифд, ифдфтсу, ьщтун]
  pay:
    description: Совершить перевод денег другому игроку
    usage: /<command> <player> <amount(В меди)>
    aliases: [зфн]