name: RBCore
main: com.skyandforest.reboot_core.Core
version: "18.32.7.6"
load: POSTWORLD
commands:
  core:
    description: ReBoot core info.
    usage: /<command> [help [admin],reload]
    aliases: [сщку]